-- pgvector extension
-- embedding 컬럼(vector(N))은 차원 수 확정 후 V3에서 추가
CREATE EXTENSION IF NOT EXISTS vector;

-- document
CREATE TABLE document (
    document_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notebook_id             BIGINT NOT NULL,
    original_file_name      VARCHAR(255) NULL,
    stored_file_name        VARCHAR(255) NULL,
    file_type               VARCHAR(10) NOT NULL,
    file_size               BIGINT NULL,
    page_count              INT NULL,
    analysis_status         VARCHAR(20) NOT NULL,
    analysis_error_message  TEXT NULL,
    uploaded_at             TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    analysis_started_at     TIMESTAMP NULL,
    analysis_finished_at    TIMESTAMP NULL,
    CONSTRAINT fk_document_notebook FOREIGN KEY (notebook_id) REFERENCES notebook (notebook_id) ON DELETE CASCADE
);

CREATE INDEX idx_document_notebook_id ON document (notebook_id);

-- source_unit
CREATE TABLE source_unit (
    source_unit_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id     BIGINT NOT NULL,
    unit_index      INT NOT NULL,
    source_type     VARCHAR(20) NOT NULL,
    heading         VARCHAR(500) NULL,
    content         TEXT NOT NULL,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_source_unit_document FOREIGN KEY (document_id) REFERENCES document (document_id) ON DELETE CASCADE
);

CREATE INDEX idx_source_unit_document_id ON source_unit (document_id);

-- section (source_unit_id FK 없음 — source_indices로 SourceUnit 범위 추적)
CREATE TABLE section (
    section_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id         BIGINT NOT NULL,
    section_order       INT NOT NULL,
    heading             VARCHAR(500) NULL,
    content             TEXT NOT NULL,
    source_start_index  INT NOT NULL,
    source_end_index    INT NOT NULL,
    source_indices      INTEGER[] NOT NULL,
    -- embedding vector(N): 차원 수 확정 후 V3에서 추가
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_section_document FOREIGN KEY (document_id) REFERENCES document (document_id) ON DELETE CASCADE
);

CREATE INDEX idx_section_document_id ON section (document_id);

-- chunk (Parent-Child Retrieval의 Child 단위 — 벡터 검색 대상)
CREATE TABLE chunk (
    chunk_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_id          BIGINT NOT NULL,
    document_id         BIGINT NOT NULL,
    chunk_order         INT NOT NULL,
    content             TEXT NOT NULL,
    source_start_index  INT NULL,
    source_end_index    INT NULL,
    source_indices      INTEGER[] NULL,
    -- embedding vector(N): 차원 수 확정 후 V3에서 추가
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_chunk_section  FOREIGN KEY (section_id)  REFERENCES section  (section_id)  ON DELETE CASCADE,
    CONSTRAINT fk_chunk_document FOREIGN KEY (document_id) REFERENCES document (document_id) ON DELETE CASCADE
);

CREATE INDEX idx_chunk_section_id  ON chunk (section_id);
CREATE INDEX idx_chunk_document_id ON chunk (document_id);

-- prompt_template
CREATE TABLE prompt_template (
    prompt_template_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prompt_version       VARCHAR(100) NOT NULL,
    system_prompt        TEXT NULL,
    user_prompt_template TEXT NULL,
    output_schema        TEXT NULL,
    is_active            BOOLEAN NULL,
    created_at           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_prompt_template_version UNIQUE (prompt_version)
);

-- generation_job
CREATE TABLE generation_job (
    job_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            BIGINT NOT NULL,
    notebook_id        BIGINT NOT NULL,
    prompt_template_id BIGINT NOT NULL,
    scope_text         TEXT NULL,
    request_type       VARCHAR(20) NOT NULL,
    difficulty         INT NULL,
    question_count     INT NULL,
    result_count       INT NULL,
    status             VARCHAR(30) NOT NULL,
    model_name         VARCHAR(100) NULL,
    created_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at         TIMESTAMP NULL,
    finished_at        TIMESTAMP NULL,
    CONSTRAINT fk_generation_job_user            FOREIGN KEY (user_id)            REFERENCES users           (user_id),
    CONSTRAINT fk_generation_job_notebook        FOREIGN KEY (notebook_id)        REFERENCES notebook        (notebook_id),
    CONSTRAINT fk_generation_job_prompt_template FOREIGN KEY (prompt_template_id) REFERENCES prompt_template (prompt_template_id)
);

CREATE INDEX idx_generation_job_user_id     ON generation_job (user_id);
CREATE INDEX idx_generation_job_notebook_id ON generation_job (notebook_id);

-- generation_context (retrieval된 Section 기록)
CREATE TABLE generation_context (
    context_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id           BIGINT NOT NULL,
    section_id       BIGINT NOT NULL,
    rank             INT NULL,
    similarity_score DECIMAL NULL,
    created_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_generation_context_job     FOREIGN KEY (job_id)     REFERENCES generation_job (job_id),
    CONSTRAINT fk_generation_context_section FOREIGN KEY (section_id) REFERENCES section        (section_id)
);

CREATE INDEX idx_generation_context_job_id ON generation_context (job_id);

-- generated_question
CREATE TABLE generated_question (
    question_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id         BIGINT NOT NULL,
    question_order INT NULL,
    type           VARCHAR(20) NULL,
    question_text  TEXT NULL,
    choices        TEXT NULL,
    answer         TEXT NULL,
    explanation    TEXT NULL,
    quality_score  DECIMAL NULL,
    created_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_generated_question_job FOREIGN KEY (job_id) REFERENCES generation_job (job_id)
);

CREATE INDEX idx_generated_question_job_id ON generated_question (job_id);

-- question_source (생성된 문제의 근거 Section 추적)
CREATE TABLE question_source (
    question_source_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id        BIGINT NOT NULL,
    section_id         BIGINT NOT NULL,
    source_order       INT NULL,
    CONSTRAINT fk_question_source_question FOREIGN KEY (question_id) REFERENCES generated_question (question_id),
    CONSTRAINT fk_question_source_section  FOREIGN KEY (section_id)  REFERENCES section            (section_id)
);

CREATE INDEX idx_question_source_question_id ON question_source (question_id);

-- question_feedback
CREATE TABLE question_feedback (
    feedback_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id          BIGINT NOT NULL,
    rating               INT NULL,
    factual_error_flag   BOOLEAN NULL,
    duplicate_flag       BOOLEAN NULL,
    difficulty_fit_score INT NULL,
    comment              TEXT NULL,
    created_at           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_question_feedback_question FOREIGN KEY (question_id) REFERENCES generated_question (question_id)
);

CREATE INDEX idx_question_feedback_question_id ON question_feedback (question_id);
