-- V3: 스키마 확장
--   1. notebook   : is_default, deleted_at 추가
--   2. document   : summary, deleted_at 추가
--   3. generated_question : is_edited, deleted_at 추가
--   4. chunk      : embedding vector(1024) 추가 (Parent-Child Retrieval — Chunk이 벡터 검색 단위)
--   5. qa_history : 노트북 Q&A + 해설 기반 Q&A 통합 테이블 신규 생성

-- 1. notebook
ALTER TABLE notebook
    ADD COLUMN is_default BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN deleted_at TIMESTAMP NULL;

-- 2. document
ALTER TABLE document
    ADD COLUMN summary    TEXT NULL,
    ADD COLUMN deleted_at TIMESTAMP NULL;

-- 3. generated_question
ALTER TABLE generated_question
    ADD COLUMN is_edited  BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN deleted_at TIMESTAMP NULL;

-- 4. chunk embedding
-- qwen3-embedding:0.6b 기준 1024차원.
-- 팀원 PC에서 curl로 실제 차원 확인 후 불일치 시 V4 migration으로 수정.
ALTER TABLE chunk
    ADD COLUMN embedding vector(1024) NULL;

-- ivfflat 인덱스는 충분한 데이터가 쌓인 뒤 별도 migration으로 추가 권장.
-- (데이터 없는 상태에서 CREATE INDEX USING ivfflat 시 recall 품질 보장 불가)
-- 추후 추가 예시:
--   CREATE INDEX idx_chunk_embedding ON chunk USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);

-- 5. qa_history
-- notebook_id: 노트북 Q&A(26번)일 때 설정, 해설 기반 Q&A(45번)일 때도 설정 가능
-- question_id: 해설 기반 Q&A(45번)일 때 설정, 노트북 Q&A(26번)일 때 NULL
-- source_section_ids: 답변 근거로 사용된 Section ID 목록 (retrieval 결과)
CREATE TABLE qa_history (
    qa_history_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            BIGINT NOT NULL,
    notebook_id        BIGINT NULL,
    question_id        BIGINT NULL,
    user_question      TEXT NOT NULL,
    ai_answer          TEXT NULL,
    answerable         BOOLEAN NOT NULL DEFAULT TRUE,
    source_section_ids INTEGER[] NULL,
    created_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_qa_history_user     FOREIGN KEY (user_id)     REFERENCES users              (user_id),
    CONSTRAINT fk_qa_history_notebook FOREIGN KEY (notebook_id) REFERENCES notebook           (notebook_id),
    CONSTRAINT fk_qa_history_question FOREIGN KEY (question_id) REFERENCES generated_question (question_id)
);

CREATE INDEX idx_qa_history_user_id     ON qa_history (user_id);
CREATE INDEX idx_qa_history_notebook_id ON qa_history (notebook_id);
CREATE INDEX idx_qa_history_question_id ON qa_history (question_id);
