-- V4: DB 스키마를 기능 명세서 기준으로 정렬
-- 용어 정비: question(문제) → quiz, qa/question(질문) 분리 명확화
-- 구조 변경: question_source / question_feedback / qa_history 제거,
--            notebook_qa_history / quiz_qa_history 분리 생성

-- ============================================================
-- 1. 삭제 대상 테이블 DROP (generated_question 의존 테이블 먼저)
-- ============================================================

DROP TABLE IF EXISTS question_feedback;
DROP TABLE IF EXISTS question_source;
DROP TABLE IF EXISTS qa_history;

-- ============================================================
-- 2. generated_question → generated_quiz
-- ============================================================

ALTER TABLE generated_question
    DROP COLUMN quality_score,
    DROP COLUMN is_edited;

ALTER TABLE generated_question RENAME COLUMN question_id    TO quiz_id;
ALTER TABLE generated_question RENAME COLUMN question_order TO quiz_order;
ALTER TABLE generated_question RENAME COLUMN type           TO quiz_type;

ALTER TABLE generated_question
    ADD COLUMN source_section_ids BIGINT[] NULL;

ALTER TABLE generated_question RENAME TO generated_quiz;

ALTER INDEX idx_generated_question_job_id RENAME TO idx_generated_quiz_job_id;

-- ============================================================
-- 3. generation_job 수정
-- ============================================================

ALTER TABLE generation_job RENAME COLUMN request_type   TO quiz_type;
ALTER TABLE generation_job RENAME COLUMN question_count TO quiz_count;

-- difficulty: INT → VARCHAR ('상' / '중' / '하')
-- 기존 데이터가 있다면 1=하, 2=중, 3=상 으로 변환
ALTER TABLE generation_job
    ALTER COLUMN difficulty TYPE VARCHAR(10)
    USING CASE difficulty
              WHEN 1 THEN '하'
              WHEN 2 THEN '중'
              WHEN 3 THEN '상'
              ELSE NULL
          END;

ALTER TABLE generation_job
    ALTER COLUMN prompt_template_id DROP NOT NULL,
    ADD COLUMN deleted_at TIMESTAMP NULL;

-- ============================================================
-- 4. users — deleted_at 추가
-- ============================================================

ALTER TABLE users
    ADD COLUMN deleted_at TIMESTAMP NULL;

-- ============================================================
-- 5. document — summary → summary_text
-- ============================================================

ALTER TABLE document RENAME COLUMN summary TO summary_text;

-- ============================================================
-- 6. section — deleted_at 추가
-- ============================================================

ALTER TABLE section
    ADD COLUMN deleted_at TIMESTAMP NULL;

-- ============================================================
-- 7. chunk — deleted_at 추가
-- ============================================================

ALTER TABLE chunk
    ADD COLUMN deleted_at TIMESTAMP NULL;

-- ============================================================
-- 8. notebook_qa_history 신규 생성
-- ============================================================

CREATE TABLE notebook_qa_history (
    qa_history_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT    NOT NULL,
    notebook_id       BIGINT    NOT NULL,
    user_question     TEXT      NOT NULL,
    ai_answer         TEXT      NOT NULL,
    answerable        BOOLEAN   NOT NULL,
    cited_section_ids BIGINT[]  NULL,
    created_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at        TIMESTAMP NULL,
    CONSTRAINT fk_notebook_qa_history_user     FOREIGN KEY (user_id)     REFERENCES users    (user_id),
    CONSTRAINT fk_notebook_qa_history_notebook FOREIGN KEY (notebook_id) REFERENCES notebook (notebook_id)
);

CREATE INDEX idx_notebook_qa_history_user_id     ON notebook_qa_history (user_id);
CREATE INDEX idx_notebook_qa_history_notebook_id ON notebook_qa_history (notebook_id);

-- ============================================================
-- 9. quiz_qa_history 신규 생성
-- ============================================================

CREATE TABLE quiz_qa_history (
    qa_history_id BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT    NOT NULL,
    quiz_id       BIGINT    NOT NULL,
    user_question TEXT      NOT NULL,
    ai_answer     TEXT      NOT NULL,
    answerable    BOOLEAN   NOT NULL,
    created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at    TIMESTAMP NULL,
    CONSTRAINT fk_quiz_qa_history_user FOREIGN KEY (user_id) REFERENCES users         (user_id),
    CONSTRAINT fk_quiz_qa_history_quiz FOREIGN KEY (quiz_id) REFERENCES generated_quiz (quiz_id)
);

CREATE INDEX idx_quiz_qa_history_user_id ON quiz_qa_history (user_id);
CREATE INDEX idx_quiz_qa_history_quiz_id ON quiz_qa_history (quiz_id);
